/* Generated By:JJTree: Do not edit this line. ASTcondition_beta.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTcondition_beta extends SimpleNode {
  public ASTcondition_beta(int id) {
    super(id);
  }

  public ASTcondition_beta(CalParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CalParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=914586a537c09f867572ddbece0bd61a (do not edit this line) */
