/* Generated By:JJTree: Do not edit this line. ASTparameter_list.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTparameter_list extends SimpleNode {
  public ASTparameter_list(int id) {
    super(id);
  }

  public ASTparameter_list(CalParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CalParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=4d40a2e1d7b631c51bbe5ecc63556ce1 (do not edit this line) */
