/* Generated By:JJTree: Do not edit this line. ASTstatement_beta.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTstatement_beta extends SimpleNode {
  public ASTstatement_beta(int id) {
    super(id);
  }

  public ASTstatement_beta(CalParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CalParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=727a5bd073304e41d72df96fe07276b5 (do not edit this line) */
