/* Generated By:JJTree: Do not edit this line. ASTvar_dec.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTvar_dec extends SimpleNode {
  public ASTvar_dec(int id) {
    super(id);
  }

  public ASTvar_dec(CalParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CalParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=4d59d186ad8c37f18dbd80f61eee9ce3 (do not edit this line) */
