/* Generated By:JavaCC: Do not edit this line. CalParserTreeConstants.java Version 5.0 */
public interface CalParserTreeConstants
{
  public int JJTPROG = 0;
  public int JJTVOID = 1;
  public int JJTVAR_DEC = 2;
  public int JJTIDENTIFIER = 3;
  public int JJTCONST_DEC = 4;
  public int JJTFUNCTION = 5;
  public int JJTRET = 6;
  public int JJTTYPE = 7;
  public int JJTPARAMETER_LIST = 8;
  public int JJTPARAMETER = 9;
  public int JJTMAIN = 10;
  public int JJTIFSTATE = 11;
  public int JJTELS = 12;
  public int JJTWHIL = 13;
  public int JJTASSIGN = 14;
  public int JJTFUNC_CALL = 15;
  public int JJTPLUS = 16;
  public int JJTMINUS = 17;
  public int JJTMINUS_IDENTIFIER = 18;
  public int JJTNUM = 19;
  public int JJTBOOL = 20;
  public int JJTAND = 21;
  public int JJTOR = 22;
  public int JJTNOT = 23;
  public int JJTEQ = 24;
  public int JJTNEQ = 25;
  public int JJTLT = 26;
  public int JJTLTE = 27;
  public int JJTGT = 28;
  public int JJTGTE = 29;
  public int JJTARG_LIST = 30;


  public String[] jjtNodeName = {
    "Prog",
    "void",
    "var_dec",
    "identifier",
    "const_dec",
    "function",
    "ret",
    "type",
    "parameter_list",
    "parameter",
    "main",
    "ifstate",
    "els",
    "whil",
    "assign",
    "func_call",
    "plus",
    "minus",
    "minus_identifier",
    "num",
    "bool",
    "and",
    "or",
    "not",
    "eq",
    "neq",
    "lt",
    "lte",
    "gt",
    "gte",
    "arg_list",
  };
}
/* JavaCC - OriginalChecksum=cdbecdcf9f9ae73fb743f51d67cf2026 (do not edit this line) */
