/* Generated By:JJTree&JavaCC: Do not edit this line. CalParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CalParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMMA = 11;
  /** RegularExpression Id. */
  int SEMIC = 12;
  /** RegularExpression Id. */
  int COLON = 13;
  /** RegularExpression Id. */
  int ASSIGN = 14;
  /** RegularExpression Id. */
  int LB = 15;
  /** RegularExpression Id. */
  int RB = 16;
  /** RegularExpression Id. */
  int PLUS = 17;
  /** RegularExpression Id. */
  int MINUS = 18;
  /** RegularExpression Id. */
  int NOT = 19;
  /** RegularExpression Id. */
  int OR = 20;
  /** RegularExpression Id. */
  int AND = 21;
  /** RegularExpression Id. */
  int EQUAL = 22;
  /** RegularExpression Id. */
  int NEQ = 23;
  /** RegularExpression Id. */
  int LT = 24;
  /** RegularExpression Id. */
  int LTE = 25;
  /** RegularExpression Id. */
  int GT = 26;
  /** RegularExpression Id. */
  int GTE = 27;
  /** RegularExpression Id. */
  int VAR = 28;
  /** RegularExpression Id. */
  int CONS = 29;
  /** RegularExpression Id. */
  int RET = 30;
  /** RegularExpression Id. */
  int INT = 31;
  /** RegularExpression Id. */
  int BOOL = 32;
  /** RegularExpression Id. */
  int VOID = 33;
  /** RegularExpression Id. */
  int MAIN = 34;
  /** RegularExpression Id. */
  int IF = 35;
  /** RegularExpression Id. */
  int ELSE = 36;
  /** RegularExpression Id. */
  int TRUE = 37;
  /** RegularExpression Id. */
  int FALSE = 38;
  /** RegularExpression Id. */
  int WHILE = 39;
  /** RegularExpression Id. */
  int BEGIN = 40;
  /** RegularExpression Id. */
  int END = 41;
  /** RegularExpression Id. */
  int IS = 42;
  /** RegularExpression Id. */
  int SSKIP = 43;
  /** RegularExpression Id. */
  int LETTER = 44;
  /** RegularExpression Id. */
  int IDENTIFIER = 45;
  /** RegularExpression Id. */
  int DIGIT = 46;
  /** RegularExpression Id. */
  int NUMBER = 47;
  /** RegularExpression Id. */
  int OTHER = 48;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_COMMENT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"/*\"",
    "<token of kind 7>",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 10>",
    "\",\"",
    "\";\"",
    "\":\"",
    "\":=\"",
    "\"(\"",
    "\")\"",
    "\"+\"",
    "\"-\"",
    "\"~\"",
    "\"|\"",
    "\"&\"",
    "\"=\"",
    "\"!=\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"variable\"",
    "\"constant\"",
    "\"return\"",
    "\"integer\"",
    "\"boolean\"",
    "\"void\"",
    "\"main\"",
    "\"if\"",
    "\"else\"",
    "\"true\"",
    "\"false\"",
    "\"while\"",
    "\"begin\"",
    "\"end\"",
    "\"is\"",
    "\"skip\"",
    "<LETTER>",
    "<IDENTIFIER>",
    "<DIGIT>",
    "<NUMBER>",
    "<OTHER>",
  };

}
