/* Generated By:JavaCC: Do not edit this line. CalParserVisitor.java Version 5.0 */
public interface CalParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTProg node, Object data);
  public Object visit(ASTvar_dec node, Object data);
  public Object visit(ASTidentifier node, Object data);
  public Object visit(ASTconst_dec node, Object data);
  public Object visit(ASTfunction node, Object data);
  public Object visit(ASTret node, Object data);
  public Object visit(ASTtype node, Object data);
  public Object visit(ASTparameter_list node, Object data);
  public Object visit(ASTparameter node, Object data);
  public Object visit(ASTmain node, Object data);
  public Object visit(ASTifstate node, Object data);
  public Object visit(ASTels node, Object data);
  public Object visit(ASTwhil node, Object data);
  public Object visit(ASTassign node, Object data);
  public Object visit(ASTfunc_call node, Object data);
  public Object visit(ASTplus node, Object data);
  public Object visit(ASTminus node, Object data);
  public Object visit(ASTminus_identifier node, Object data);
  public Object visit(ASTnum node, Object data);
  public Object visit(ASTbool node, Object data);
  public Object visit(ASTand node, Object data);
  public Object visit(ASTor node, Object data);
  public Object visit(ASTnot node, Object data);
  public Object visit(ASTeq node, Object data);
  public Object visit(ASTneq node, Object data);
  public Object visit(ASTlt node, Object data);
  public Object visit(ASTlte node, Object data);
  public Object visit(ASTgt node, Object data);
  public Object visit(ASTgte node, Object data);
  public Object visit(ASTarg_list node, Object data);
}
/* JavaCC - OriginalChecksum=f9e205bc9e504c43e0703e25550ba195 (do not edit this line) */
